#!/bin/bash
#
# Ensures a website returns the expected results

# Requires /usr/bin/time to be GNU Time.  BSD won't work.


# executing the configuration is potentially a security risk.
# TODO: replace with a proper config file?
. ./config.sh

result="$(/bin/date +%F_%H-%M-%S-%Z)-result.html"

# --fail just says don't output the progress bar to stdout, and don't
echo -ne "\"$(/bin/date +"%Y-%m-%d %H:%M:%S")\"," >> command-times.csv
output="$(/usr/bin/time -a -o >(tr -d '\n' >> command-times.csv) -f %e --quiet \
  curl --fail --silent --show-error -m "$TIMEOUT" -o "$result" "$URL" 2>&1)"
if [ $? = 0 ]; then
  if [ ! -f expected.html ]; then
    echo ',"need an `expected.html` file."' >> command-times.csv
    exit 1
  elif ! diff expected.html "$result" > "$root.diff"; then
    # log error to screen
    echo "UNEXPECTED OUTPUT:"
    cat "$root.diff"
    # log error to file
    printf "\n\n\n$result:\n" >> command-errors.txt
    cat "$root.diff" >> command-errors.txt
  fi

  rm "$root.diff" "$result"
else
  echo ",\"$output\"" >> command-times.csv
fi
